CREATE EXTERNAL TABLE awards_hive
(
	SEASON INT
  	,SUPERBOWL_CHAMP VARCHAR(5)
  	,AFC_CHAMP VARCHAR(5)
  	,NFC_CHAMP VARCHAR(5)
  	,MVP VARCHAR(30)
  	,OFF_ROOKIE VARCHAR(30)
  	,DEF_ROOKIE VARCHAR(30)
  	,DEF_POY VARCHAR(30)
  	,PASS_LEADER VARCHAR(30)
  	,RUSH_LEADER VARCHAR(30)
  	,REC_LEADER VARCHAR(30)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION 'wasbs:///awards-hive.csv'
TBLPROPERTIES("skip.header.line.count"="1");