CREATE EXTERNAL TABLE draft_hive
(
	ROUND INT
  	,PICK INT
  	,TEAM VARCHAR(5)
  	,PLAYER_NAME VARCHAR(30)
  	,POS VARCHAR(5)	
  	,DRAFTED_AGE INT
  	,FINAL_SEASON INT
  	,ALL_PRO_SELECTIONS INT
  	,PRO_BOWL INT
  	,PRIMARY_STARTER INT
  	,WEIGHTED_APPROX_VAL INT
  	,DRAFT_APPROX_VAL INT
  	,GAMES_PLAYED INT
  	,CAREER_PASSING_COMPLETIONS INT
  	,CAREER_PASSING_ATTEMPTS INT
  	,CAREER_PASSING_YARDS INT
  	,CAREER_PASSING_TD INT
  	,CAREER_PASSING_INT INT
  	,CAREER_RUSHING_ATTEMPTS INT
  	,CAREER_RUSHING_YARDS INT
  	,CAREER_RUSHING_TD INT
  	,CAREER_RECEIVING_RECEPTIONS INT
  	,CAREER_RECEIVING_YARDS INT
  	,CAREER_RECEIVING_TD INT
  	,CAREER_TACKLES INT
  	,CAREER_INTERCEPTIONS INT
  	,CAREER_SACKS FLOAT
  	,COLLEGE VARCHAR(30)
  	,DRAFT_YEAR INT
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION 'wasbs:///draft-hive.csv'
TBLPROPERTIES("skip.header.line.count"="1");