CREATE EXTERNAL TABLE pass_hive
(
	RANK INT
  	,PLAYER_NAME VARCHAR(30)
  	,TEAM VARCHAR(5)
  	,AGE INT
  	,POS VARCHAR(5)
  	,GAMES_PLAYED INT
  	,GAMES_STARTED INT
  	,QB_REC VARCHAR(10)
  	,COMPLETIONS INT
  	,ATTEMPTS INT
  	,COMPLETION_PERCENTAGE FLOAT
  	,YARDS INT
  	,TD INT
  	,TD_PERCENT FLOAT
  	,INTERCEPTIONS INT
  	,INT_PERCENT FLOAT
  	,LONGEST_PASS INT
  	,YARDS_PER_ATTEMPT FLOAT
  	,ADJ_YARDS_PER_ATTEMPT FLOAT
  	,YARDS_PER_COMPLETION FLOAT
  	,YARDS_PER_GAME FLOAT
  	,QB_RATE FLOAT
  	,ADJ_QB_RATE FLOAT
  	,SACKS_TAKEN INT
  	,YARDS_SACK INT
  	,NET_YARDS_PER_PASS FLOAT
  	,ADJ_NET_YARDS_PER_PASS FLOAT
  	,SACK_PERCENT FLOAT
  	,FOURTH_QTR_COMEBACK INT
  	,GAME_WINNING_DRIVE INT
  	,YEAR INT
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION 'wasbs:///pass-hive.csv'
TBLPROPERTIES("skip.header.line.count"="1");
