CREATE EXTERNAL TABLE rec_hive
(
	RANK INT
  	,PLAYER_NAME VARCHAR(30)
  	,TEAM VARCHAR(5)
  	,AGE INT
  	,POS VARCHAR(5)
  	,GAMES_PLAYED INT
  	,GAMES_STARTED INT
  	,TARGET INT
  	,RECEPTIONS INT
  	,CATCH_PERCENTAGE FLOAT
  	,YARDS INT
  	,YARDS_PER_REC FLOAT
  	,TD INT
  	,LONGEST_REC INT
  	,REC_PER_GAME FLOAT
  	,YARDS_PER_GAME FLOAT
  	,FMBLS INT
  	,YEAR INT
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION 'wasbs:///rec-hive.csv'
TBLPROPERTIES("skip.header.line.count"="1");
